print("........................................")
print("             ppppppppppppppp            ")
print("          pp                 pp         ")
print("         pp                   pp        ")
print("        pp      pp     pp      pp       ")
print("       pp       pp     pp       pp      ")
print("       pp                       pp      ")
print("       pp    pp           pp    pp      ")
print("        pp     pp       pp     pp       ")
print("         pp       ppppp       pp        ")
print("          pp                 pp         ")
print("             ppppppppppppppp            ")
print("........................................")